layout_spectrum: 0.21766913519240916
typography_spectrum: 0.7350216964259744
color:
  brandStrength: 0.39600283722393215
  lightness: 0.011784464353695512
  saturation: 0.4984742838423699
  rhythmicContrast: 0.4916455140337348
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Gian Mancuso
