typography_spectrum: 0.7350216964259744
color:
  brandStrength: 0.39600283722393215
  lightness: 0.011784464353695512
  saturation: 0.4984742838423699
  rhythmicContrast: 0.4916455140337348
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
layout_spectrum: 0.21766913519240916
name: 'Gian Mancuso, MA PMP'
navigation:
  - name: Get in Touch
    id: d016ec3a-818c-4678-ac11-bbe2a4776b32
    type: content
  - name: Metaphor and Mental Models
    id: 4f9aefef-74db-45fd-a78f-410feb415f4d
    type: content
  - name: Cross-Platform Design
    id: 1219dfce-3648-423b-bee2-0cea5a29fd24
    type: content
title: An Experience Design Portfolio
description: 'We all feel a little nostalgic for tomorrow, sometimes'
