typography_spectrum: 0.7350216964259744
color:
  brandStrength: 0.39600283722393215
  lightness: 0.011784464353695512
  saturation: 0.4984742838423699
  rhythmicContrast: 0.4916455140337348
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
layout_spectrum: 0.21766913519240916
name: 'Gian Mancuso, MA PMP'
title: An Experience Design Portfolio
description: 'We all feel a little nostalgic for tomorrow, sometimes'
